[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "api/health"
healthcheckTimeout = 10

[variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
SESSION_DRIVER = "cookie"
