[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 10

[variables]
DB_CONNECTION = "pgsql"
DB_HOST = "${PGHOST}"
DB_PORT = "${PGPORT}"
DB_DATABASE = "${PGDATABASE}"
DB_USERNAME = "${PGUSER}"
DB_PASSWORD = "${PGPASSWORD}"
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
