[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 10

[variables]
DB_CONNECTION = "pgsql"
DB_HOST = "${PGHOST}"
DB_PORT = "${PGPORT}"
DB_DATABASE = "${PGDATABASE}"
DB_USERNAME = "${PGUSER}"
DB_PASSWORD = "${PGPASSWORD}"
